//RoleAssignments actions
export const ROLEASSIGNMENTS_LOADING = "ROLEASSIGNMENTS_LOADING";
export const GET_ROLEASSIGNMENT = "GET_ROLEASSIGNMENT";
export const GET_ROLEASSIGNMENTS = "GET_ROLEASSIGNMENTS";
