//Process publications types actions
export const PUBLICATIONTYPES_LOADING = "PUBLICATIONTYPES_LOADING";
export const GET_PUBLICATIONTYPE = "GET_PUBLICATIONTYPE";
export const GET_PUBLICATIONTYPES = "GET_PUBLICATIONTYPES";
