/** @format */

//Error actions
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

//Process actions
export const PROCESS_LOADING = 'PROCESS_LOADING'
export const GET_PROCESS = 'GET_PROCESS'
export const GET_PROCESSES = 'GET_PROCESSES'
export const GET_PROCESS_FILTERS = 'GET_PROCESS_FILTERS'

//CallV2 actions
export const LOADING_CALLV2 = 'LOADING_CALLV2'
export const CREATE_CALLV2 = 'CREATE_CALLV2'
export const READ_CALLV2 = 'READ_CALLV2'
export const UPDATE_CALLV2 = 'UPDATE_CALLV2'
export const DELETE_CALLV2 = 'DELETE_CALLV2'
export const LIST_CALLV2 = 'LIST_CALLV2'

//VacancyV2 actions
export const LOADING_VACANCY = 'LOADING_VACANCY'
export const CREATE_VACANCY = 'CREATE_VACANCY'
export const READ_VACANCY = 'READ_VACANCY'
export const UPDATE_VACANCY = 'UPDATE_VACANCY'
export const DELETE_VACANCY = 'DELETE_VACANCY'
export const READ_LIST_VACANCY = 'READ_LIST_VACANCY'

//AssignmentV2 actions
export const LOADING_ASSIGNMENTV2 = 'LOADING_ASSIGNMENTV2'
export const CREATE_ASSIGNMENTV2 = 'CREATE_ASSIGNMENTV2'
export const READ_ASSIGNMENTV2 = 'READ_ASSIGNMENTV2'
export const UPDATE_ASSIGNMENTV2 = 'UPDATE_ASSIGNMENTV2'
export const DELETE_ASSIGNMENTV2 = 'DELETE_ASSIGNMENTV2'
export const READ_LIST_ASSIGNMENTV2 = 'READ_LIST_ASSIGNMENTV2'

//RegionV2 actions
export const LOADING_REGIONV2 = 'LOADING_REGIONV2'
export const CREATE_REGIONV2 = 'CREATE_REGIONV2'
export const READ_REGIONV2 = 'READ_REGIONV2'
export const UPDATE_REGIONV2 = 'UPDATE_REGIONV2'
export const DELETE_REGIONV2 = 'DELETE_REGIONV2'
export const READ_LIST_REGIONV2 = 'READ_LIST_REGIONV2'

//RegionV2 actions
export const LOADING_RESTRICTIONV2 = 'LOADING_RESTRICTIONV2'
export const CREATE_RESTRICTIONV2 = 'CREATE_RESTRICTIONV2'
export const READ_RESTRICTIONV2 = 'READ_RESTRICTIONV2'
export const UPDATE_RESTRICTIONV2 = 'UPDATE_RESTRICTIONV2'
export const DELETE_RESTRICTIONV2 = 'DELETE_RESTRICTIONV2'
export const READ_LIST_RESTRICTIONV2 = 'READ_LIST_RESTRICTIONV2'

//Calendar actions
export const LOADING_CALENDAR = 'LOADING_CALENDAR'
export const CREATE_CALENDAR = 'CREATE_CALENDAR'
export const READ_CALENDAR = 'READ_CALENDAR'
export const UPDATE_CALENDAR = 'UPDATE_CALENDAR'
export const DELETE_CALENDAR = 'DELETE_CALENDAR'
export const READ_LIST_CALENDAR = 'READ_LIST_CALENDAR'
