/** @format */

//Error actions
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

//Process actions
export const PROCESS_LOADING = 'PROCESS_LOADING'
export const GET_PROCESS = 'GET_PROCESS'
export const GET_PROCESSES = 'GET_PROCESSES'
export const GET_PROCESS_FILTERS = 'GET_PROCESS_FILTERS'

//Call actions
export const LOADING_CALL = 'LOADING_CALL'
export const CREATE_CALL = 'CREATE_CALL'
export const READ_CALL = 'READ_CALL'
export const UPDATE_CALL = 'UPDATE_CALL'
export const DELETE_CALL = 'DELETE_CALL'
export const LIST_CALLV2 = 'LIST_CALLV2'

//Vacancy actions
export const LOADING_VACANCY = 'LOADING_VACANCY'
export const CREATE_VACANCY = 'CREATE_VACANCY'
export const READ_VACANCY = 'READ_VACANCY'
export const UPDATE_VACANCY = 'UPDATE_VACANCY'
export const DELETE_VACANCY = 'DELETE_VACANCY'
export const READ_LIST_VACANCY = 'READ_LIST_VACANCY'

//AssignmentV2 actions
export const LOADING_ASSIGNMENTV2 = 'LOADING_ASSIGNMENTV2'
export const CREATE_ASSIGNMENTV2 = 'CREATE_ASSIGNMENTV2'
export const READ_ASSIGNMENTV2 = 'READ_ASSIGNMENTV2'
export const UPDATE_ASSIGNMENTV2 = 'UPDATE_ASSIGNMENTV2'
export const DELETE_ASSIGNMENTV2 = 'DELETE_ASSIGNMENTV2'
export const READ_LIST_ASSIGNMENTV2 = 'READ_LIST_ASSIGNMENTV2'

//RegionV2 actions
export const LOADING_REGIONV2 = 'LOADING_REGIONV2'
export const CREATE_REGIONV2 = 'CREATE_REGIONV2'
export const READ_REGIONV2 = 'READ_REGIONV2'
export const UPDATE_REGIONV2 = 'UPDATE_REGIONV2'
export const DELETE_REGIONV2 = 'DELETE_REGIONV2'
export const READ_LIST_REGIONV2 = 'READ_LIST_REGIONV2'

//RegionV2 actions
export const LOADING_RESTRICTIONV2 = 'LOADING_RESTRICTIONV2'
export const CREATE_RESTRICTIONV2 = 'CREATE_RESTRICTIONV2'
export const READ_RESTRICTIONV2 = 'READ_RESTRICTIONV2'
export const UPDATE_RESTRICTIONV2 = 'UPDATE_RESTRICTIONV2'
export const DELETE_RESTRICTIONV2 = 'DELETE_RESTRICTIONV2'
export const READ_LIST_RESTRICTIONV2 = 'READ_LIST_RESTRICTIONV2'

//Calendar actions
export const LOADING_CALENDAR = 'LOADING_CALENDAR'
export const CREATE_CALENDAR = 'CREATE_CALENDAR'
export const READ_CALENDAR = 'READ_CALENDAR'
export const UPDATE_CALENDAR = 'UPDATE_CALENDAR'
export const DELETE_CALENDAR = 'DELETE_CALENDAR'
export const READ_LIST_CALENDAR = 'READ_LIST_CALENDAR'

//InscriptionEvent actions
export const LOADING_INSCRIPTIONEVENT = 'LOADING_INSCRIPTIONEVENT'
export const CREATE_INSCRIPTIONEVENT = 'CREATE_INSCRIPTIONEVENT'
export const READ_INSCRIPTIONEVENT = 'READ_INSCRIPTIONEVENT'
export const UPDATE_INSCRIPTIONEVENT = 'UPDATE_INSCRIPTIONEVENT'
export const DELETE_INSCRIPTIONEVENT = 'DELETE_INSCRIPTIONEVENT'
export const READ_LIST_INSCRIPTIONEVENT = 'READ_LIST_INSCRIPTIONEVENT'

//Inscription actions
export const LOADING_INSCRIPTION = 'LOADING_INSCRIPTION'
export const CREATE_INSCRIPTION = 'CREATE_INSCRIPTION'
export const READ_INSCRIPTION = 'READ_INSCRIPTION'
export const UPDATE_INSCRIPTION = 'UPDATE_INSCRIPTION'
export const DELETE_INSCRIPTION = 'DELETE_INSCRIPTION'
export const READ_LIST_INSCRIPTION = 'READ_LIST_INSCRIPTION'
