//Process actions
export const GET_PROCESS = "GET_PROCESS";
export const GET_PROCESSES = "GET_PROCESSES";
export const PROCESS_LOADING = "PROCESS_LOADING";
export const GET_STEPTYPES_OPTIONS = "GET_STEPTYPES_OPTIONS";
export const GET_ASSIGNMENTS_OPTIONS = "GET_ASSIGNMENTS_OPTIONS";
