//GraduationTypes actions
export const LOADING_GRADUATIONTYPES_V2 = 'LOADING_GRADUATIONTYPES_V2'
export const CREATE_GRADUATIONTYPE_V2 = 'CREATE_GRADUATIONTYPE_V2'
export const READ_GRADUATIONTYPE_V2 = 'READ_GRADUATIONTYPE_V2'
export const UPDATE_GRADUATIONTYPE_V2 = 'UPDATE_GRADUATIONTYPE_V2'
export const DELETE_GRADUATIONTYPE_V2 = 'DELETE_GRADUATIONTYPE_V2'
export const LIST_GRADUATIONTYPE_V2 = 'LIST_GRADUATIONTYPE_V2'
