//PermissionAssignments actions
export const PERMISSIONASSIGNMENTS_LOADING = "PERMISSIONASSIGNMENTS_LOADING";
export const GET_PERMISSIONASSIGNMENT = "GET_PERMISSIONASSIGNMENT";
export const GET_PERMISSIONASSIGNMENTS = "GET_PERMISSIONASSIGNMENTS";
