//Process publications types actions
export const PROCESSPUBLICATIONTYPES_LOADING =
  "PROCESSPUBLICATIONTYPES_LOADING";
export const GET_PROCESSPUBLICATIONTYPE = "GET_PROCESSPUBLICATIONTYPE";
export const GET_PROCESSPUBLICATIONTYPES = "GET_PROCESSPUBLICATIONTYPES";
