//RoleAssignments actions
export const PROCESSPUBLICATIONS_LOADING = "PROCESSPUBLICATIONS_LOADING";
export const GET_PROCESSPUBLICATION = "GET_PROCESSPUBLICATION";
export const GET_PROCESSPUBLICATIONS = "GET_PROCESSPUBLICATIONS";
