//PermissionAssignments actions
export const ROLEPERMISSIONS_LOADING = "ROLEPERMISSIONS_LOADING";
export const GET_ROLEPERMISSION = "GET_ROLEPERMISSION";
export const GET_ROLEPERMISSIONS = "GET_ROLEPERMISSIONS";
