//PermissionTypes actions
export const PERMISSIONTYPES_LOADING = "PERMISSIONTYPES_LOADING";
export const GET_PERMISSIONTYPE = "GET_PERMISSIONTYPE";
export const GET_PERMISSIONTYPES = "GET_PERMISSIONTYPES";
