//GraduationTypes actions
export const GRADUATIONTYPES_LOADING = "GRADUATIONTYPES_LOADING";
export const GET_GRADUATIONTYPE = "GET_GRADUATIONTYPE";
export const GET_GRADUATIONTYPES = "GET_GRADUATIONTYPES";
